### PR TITLE
fixes #35 enable unaccent extension

### LINKED ISSUE #35: Cautarea in listele de voluntari sau comunitate sa fie latin (fara diacritice)
La cautarea unei persoane in listele de voluntari/comunitate sa se ignore diacriticele care apar in nume.
Exemplu: "Cătălina" sa poata fi gasita si cautand "Catalina"

### PR DESCRIPTION
**Pull request by mess110**
Fixes #35 

More info about the solution:

https://www.postgresql.org/docs/9.1/static/unaccent.html
http://stackoverflow.com/a/9269859/642778

PS: I assume we use postgres > 9.1

### CODE REVIEW

**Comment by mess110** [comment]
The tests were failing because I didn't include schema.rb in the initial commit. The reason why I didn't do that is because some tables were also removed from the schema after rake db:migrate. I tried to find more information about the tables "communications" and "recipients".

I found that they were added in commit defb690c95a28ef8c8839aaac5ba32f0e0365109 but I didn't find the models. At the moment, I suspect those tables are not used. Can you please confirm @rusanu ?

**Comment by rusanu** [comment]
@mess110  There are some tables created in branches that were not merged into master. Since I don't have a different  dev DB for each branch,I think schema.rb picks up these tables, even though there is no migration for them.

**Comment by mess110** [comment]
@shotgundebugging code review pls?

**Comment by shotgundebugging** [comment]
I reviewed it, even tough it's merged. I just checked and the default `unaccent.rules` file also handles ș and ț.

**Pull request merged**
